# config.yaml
optimizer_params:
  - name: PSD-ACCEL-dap-mom-ns-nadam-0.95-0.999
    lr: [0.001, 0.003]
    dap_beta1: 0.95
    dap_beta2: 0.999
    momentum: 0
    wd: 0
    disable_preconditioning: False
    scalar: False
    ns_pinv_steps: 50
    damping: 0
    nesterov: True
    weight_decay: 0.0
    lr_schedule: constant-linear
    warm_up_fraction: 0.4
    adagradnorm: False
    rcond: 1e-3
    accelerated: add_eps_1e-3

training_params:
  tokens_processed: 524288 # 2^19
  val_tokens_processed: 8388608 #2^23
  batch_size: 32
  num_epochs: 1
  context_length: 1024
  gradnorm: 1.0
  tensorcore_precision: highest   #Can be highest, high, or medium
  autocast: True
  mixed_precision: bfloat16
  compile: True

logging_params:
  val_tokens_processed: 8388608 #2^23
  log_step: 256
  val_step: 256
  save_ckpt_step: 512
  load_ckpt_step: 0
  keep_last: 2
  ckpt_dir: "" #/mnt/ceph/users/cmodi/gptopt/

gpt_model:
  n_embd: 768    
  n_layer: 12   
  n_head: 12    
  vocab_size: 50257
  flash_attention: True

dataset:
  name: "fineweb1B"
