# config.yaml
optimizer_params:
  - name: dap-mom
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    lr_schedule: constant
    ema_beta: 0
    momentum: 0.95
    wd: 0
    sgd_update: False
    scalar: False

  - name: dap-ns-50
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    lr_schedule: constant
    ema_beta: 0
    momentum: 0
    wd: 0
    sgd_update: False
    scalar: False
    ns_pinv_steps: 50

  - name: dap-mom-ns-50
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    lr_schedule: constant
    ema_beta: 0
    momentum: 0.95
    wd: 0
    sgd_update: False
    scalar: False
    ns_pinv_steps: 50

training_params:
  tokens_processed: 4096 # 2^11  # 524288 # 2^19
  val_tokens_processed: 8388608 #2^23
  batch_size: 4
  num_epochs: 1
  context_length: 512
  gradnorm: 0.0  # Removed testing polyak stepsizes
  tensorcore_precision: high   #Can be highest, high, or medium
  autocast: True
  mixed_precision: bfloat16
  compile: False

logging_params:
  val_tokens_processed: 2048 #2^23
  log_step: 50
  val_step: 50
  save_ckpt_step: 500
  load_ckpt_step: 0
  keep_last: 2
  ckpt_dir: "" #/mnt/ceph/users/cmodi/gptopt/
  
gpt_model:
  n_embd: 256    # Smaller embedding dimension
  n_layer: 2     # Fewer transformer layers
  n_head: 4      # Fewer attention heads
  vocab_size: 50257
  flash_attention: True

dataset:
  name: "tiny_shakespeare"  
